/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'An incremental text adventure': '一款文字冒险增量游戏',
    'New Game': '新游戏',
    'Vikingcrement': '维京增量',
    '<strong>We\'re sorry but vikincremental doesn\'t work properly without JavaScript enabled. Please enable it to continue.</strong>': '<strong>很抱歉，如果没有启用 JavaScript，vikincremental 将无法正常工作。 请启用它以继续。</strong>',
    'Deer Rug': '鹿皮地毯',
    'Delve': '副本',
    'Reset': '重置',
    'Pause': '暂停',
    'Pertains mostly to woodworking and other simple crafts.': '主要涉及木工和其他简单的工艺品。',
    'Processing': '加工',
    'Proving Grounds': '试验场',
    'Queen Bee': '女王蜂',
    'Remove': '移除',
    'A verdant paradise of sprawling hillsides dotted with trees and shrubbery.': '广阔的山坡上点缀着树木和灌木丛，是一片青翠的天堂。',
    'An inspiration to greet you at the dawn of each day.': '在每一天的黎明迎接你的灵感。',
    'Also at the start of each day is the chance for a random enemy encounter. The encounter chance is based on the number of vikings in your party, as well as your comfort level and fortification level.': '此外，每天开始时都有机会遇到随机敌人。 遭遇机会取决于您队伍中维京人的数量，以及您的舒适度和防御工事水平。',
    'A comfort for cooking, shelter, rest, and more.': '烹饪、住所、休息等的舒适环境。',
    'A Goblin Youngling has entered the battlefield!': '有哥布林幼崽登上了战场！',
    'A necessity for creating basic arms and armor.': '创建基本武器和盔甲的必要条件。',
    'Stone': '石头',
    'Swipe': '滑动',
    'Tanning Rack': '鞣架',
    'Tasks': '任务',
    'Steer Rug': '斯蒂尔地毯',
    'Longhouse': '长屋',
    'Large Bone': '大骨头',
    'Leather Scraps': '皮革废料',
    'Inventory': '库存',
    'Instruction Manual': '使用说明书',
    'Item Rate Modifier': '物品率修改器',
    'Kiln': '窑',
    'Tasks are generally controlled by equipment, but in some cases certain workshop items must be built before a task can be used. Tasks use up stamina so balancing the work of each viking is vital to sucecss.': '任务通常由装备控制，但在某些情况下，必须先建造某些车间物品才能使用任务。 任务会消耗耐力，因此平衡每个维京人的工作对于成功至关重要。',
    'The basis for crafting advanced arms and armor.': '制作高级武器和盔甲的基础。',
    'The basis for staving off hunger.': '避免饥饿的基础。',
    'The Cycle of Death and Rebirth': '死亡和重生周期',
    'The Day Cycle': '日循环',
    'The dense hide provides a soft floor.': '密集的皮革提供柔软的地板。',
    'The foundation of making a house a home, and more.': '让房子成为家的基础等等。',
    'The original goal was to translate as much of Valheim as I could into a text-based incremental game.': '我最初的目标是将《Valheim》中的内容尽可能地转换成基于文本的增量游戏。',
    'The Proving Grounds are where vikings go to test their mettle. In Delves, vikings will explore randomly generated dungeons filled with treasure, enemies, and key items for facing each boss.': '试验场是维京人测试他们勇气的地方。 在 副本 中，维京人将探索随机生成的地牢，里面装满了宝藏、敌人和关键物品，以面对每个Boss。',
    'Housing': '住房',
    'Housing determines the maximum number of vikings available in your party. New houses will become available as your progress through the world. As you improve your housing, enemies will find you a more attractive target.': '住房决定了您的队伍中可用的维京人的最大数量。 随着您在世界各地的进步，新房子将可用。 当你改善你的住房时，敌人会发现你是一个更有吸引力的目标。',
    'Leather Armor': '皮甲',
    'Leather Greaves': '皮革护胫',
    'Leather Helmet': '皮头盔',
    'Resin': '树脂',
    'Reviving costs Ichor and increases with the power of your vikings. You are able to sell off gear you have accumulated in exchange for Ichor.': '复活会消耗灵液并随着维京人的力量而增加。 你可以卖掉你积累的装备来换取灵液。',
    'show | hide': '显示 | 隐藏',
    'Small Game Hunting': '小型狩猎',
    'Smelter': '冶炼厂',
    'Small House': '小房子',
    'The soft deer skin helps to sleep through the night': '柔软的鹿皮有助于整夜安眠',
    'The start of any homestead.': '任何宅基地的开始。',
    'The tools for smithing and crafting with metals.': '用于锻造和制作金属的工具。',
    'The warm, thick furs make sleep even more delightful.': '温暖厚实的毛皮让睡眠更加愉悦。',
    'The workshop is where all of the tools to prosper can be found.': '车间是可以找到所有达到繁荣工具的地方。',
    'Vikincrement': '维京增量',
    'Vikincremental is part incremental/idle game, part text adventure, and part resource management game. Manage a party of vikings through treacherous lands by performing tasks, exploring dungeons, and challenging bosses.': '维京增量是部分增量/空闲游戏、部分文本冒险和部分资源管理游戏。 通过执行任务、探索地牢和挑战老板，在危险的土地上管理一群维京人。',
    'Vikincremental works on a day cycle of 24 hours. At the beginning of each day your vikings will rest, if able, restoring and improving their health and stamina for the day. Each viking will eat independently so make sure you have enough food for all. Resting is only possible with beds and a fire, so be sure to prioritize those items!': '维京增量的工作周期为 24 小时。 在每天开始时，您的维京人会休息，如果可以的话，恢复和改善他们当天的健康和耐力。 每个维京人都会独立进食，因此请确保您有足够的食物供所有人食用。 只有床和火才能休息，所以一定要优先考虑这些物品！',
    'Vikings': '维京人',
    'What is Vikincremental?': '什么是维京增量？',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'Tough Hide': '硬皮',
    'Leather Hide': '毛皮',
    'Wolf Hide': '狼皮',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Mushrooms: ": "蘑菇: ",
    "Stamina Regen: ": "耐力恢复: ",
    "Leather Hide: ": "皮革隐藏: ",
    "Leather Scraps: ": "皮革废料: ",
    "Stamina: ": "耐力: ",
    "Resin: ": "树脂: ",
    "Wood: ": "木头: ",
    "Honey: ": "蜂蜜: ",
    "Stone: ": "石头: ",
    "Stone Axe": "石斧",
    "Ichor: ": "灵液: ",
    "Vikings: ": "维京人: ",
    "Acc: ": "命中: ",
    "New crafting item unlocked: ": "解锁了新的工艺物品：",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    " has defeated Goblin Youngling!": "打败了哥布林幼崽！",
    " hits Goblin Youngling for 15 damage and uses 15 stamina!": "击中地精幼崽造成 15 点伤害并消耗 15 耐力！",
    " misses and uses 15 stamina...": "未命中并消耗了 15 耐力...",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Legs, (.+) armor$/, '腿部, 2 护甲'],
    [/^Starting day (.+) on the battlefield...$/, '从第 $1 天开始在战场上......'],
    [/^Day: (.+)$/, '天：$1'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);